name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    name: Tests (${{ matrix.os }} / py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.9", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install maturin pytest polars

      - name: Build extension (editable)
        run: |
          maturin develop --release -m pyproject.toml

      - name: Run tests
        run: pytest -q

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Clippy (no-deps)
        run: cargo clippy --no-deps -D warnings

